### ISSUE TITLE
Setting Visual Studio defaults

### ISSUE THREAD

**Issue by JTravis76** [lextm/iisexpress-cors#2]
Thanks so much for figuring this out. Spend a hour or two trying to get to work before I ran across this.

Just for anyone who may see this.
To adjust the default **applicationhost.config** for Visual Studio, run this script against 
`C:\Program Files (x86)\IIS Express\config\templates\PersonalWebServer\applicationhost.config`.

Then delete the **applicationhost.config** in the `.vs` along side your project. Rerun your web app and Visual Studio will copy default into your project, taking the pain out of CORS.

**Comment by lextm** [comment]
You can learn from readme that actually the scripts allow you to run on any .config file, such as `install.ps1 -fileName custom.config`.

I personally don't think changing VS defaults is a good idea, as Microsoft mainly tested its products on such defaults. Changing them can lead to unexpected bugs elsewhere.

**Comment by JTravis76** [comment]
Good point. Thanks again for this script. It was a pain to open fiddler to get CORS to work with Window Authentication. Now it's all F5 and debugging from here :)
