### ISSUE TITLE
install errors

### ISSUE THREAD

**Issue by jamersoniiv** [lextm/iisexpress-cors#4]
Hi, I've tried runing this and end up with the following,

I got 3 warnings:
WARNING: Cannot find the original schema.
WARNING: Cannot find module 32 bit.
WARNING: Cannot find module 64 bit.

it then added section cors.
Added global module.
Added module

Remove-Item : Cannot find path 'C:\Users\jam\AppData\Local\Temp\IISCORS-6c34139e' because it does not exist.
At C:\users\jam\desktop\cors\install.ps1:140 char:5
+     Remove-Item $tempDirPath -Recurse
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\jam...ISCORS-6c34139e:String) [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand

**Comment by lextm** [comment]
What exactly was the command line you execute?

**Comment by lballena** [comment]
<img width="862" alt="image" src="https://github.com/lextm/iisexpress-cors/assets/69644283/1ed46673-8fd9-4faf-a752-a59e833a2d1b">

Was this issue solved?  I have the same problem.  I attached my screenshot and how I ran it.

**Comment by lextm** [comment]
The install script tries to clean up extracted files from the MSI package in this step,

https://github.com/lextm/iisexpress-cors/blob/master/install.ps1#L182

But for some unknown reasons (likely something installed on your machine) there was nothing to delete and this error occurred.

You don't need to take any further action, as the installation already finished and IIS Express has been patched.

**Comment by lballena** [comment]
I appreciate the quick reply.  Unfortunally, IISExpress will not start.  

<img width="218" alt="image" src="https://github.com/lextm/iisexpress-cors/assets/69644283/c88e6c62-fa3b-48d0-b8ad-ae6399de1e9b">

I ended up running the /trace:error in powershell cmd line, and it looks like missing module

<img width="755" alt="image" src="https://github.com/lextm/iisexpress-cors/assets/69644283/a899db5e-8947-491f-b4bd-71c43cd0e61e">

Something didn't get installed correctly.   I did run the msi by itself...looks like there's dependencies...
<img width="391" alt="image" src="https://github.com/lextm/iisexpress-cors/assets/69644283/5a06a0f3-cd65-454d-8a26-20779ef84cd3">

Possibly the issue.  Thank you again though for the quick reply.

**Comment by lextm** [comment]
Thanks. That actually explained further on what was the cause.

This machine does not have IIS installed, so that the CORS module MSI package cannot be executed properly (because it requires IIS). As a result, the install script cannot extract the needed files either.

I just pushed a new version, which switches the MSI extraction to lessmsi. You can give that a try and let me know if everything starts to work.
